arm_controller:
    type: position_controllers/JointTrajectoryController
    publish_rate: 50
    joints:
      - p0_joint
      - p1_joint
      - p2_joint
      - p3_joint
      - gripper_1
      - gripper_2